env:
  global:
    - CC_TEST_REPORTER_ID=67b206e6a4d0139f248afa12e5aef02761d90c49478425b0ca130249638076e7

language: python

python:
  - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest --cov=athom --cov-report xml tests

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
